server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jloprod90/spring.git
        default-label: main
        search-paths:
          - '*service*'
